version: '3.8'

services:
  django_gunicorn:
    build: .
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: ["/app/entrypoint.sh"]
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
    depends_on:
      - django_gunicorn

volumes:
  static:
